<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://bun.net/schema/v1" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://bun.net/schema/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
	<types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://bun.net/schema/v1" elementFormDefault="qualified">
			<xs:include schemaLocation="Bun.xsd"/>
		</xs:schema>
	</types>
	<portType name="BunPortType">
		<operation name="createParty">
			<input message="tns:CreatePartyRequest"/>
			<output message="tns:CreatePartyResponse"/>
		</operation>
	</portType>
	<binding name="BunPortSOAP11Binding" type="tns:BunPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="createParty">
			<soap:operation/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<message name="CreatePartyRequest">
		<part name="Party" element="tns:Party"/>
	</message>
	<message name="CreatePartyResponse">
		<part name="Status" element="tns:Status"/>
	</message>
	<service name="BunService">
		<port name="BunPort" binding="tns:BunPortSOAP11Binding"/>
	</service>
</definitions>